README.md

Add minimum viable context to README

---

.codeclimate.yml
ci/credentials.example.yml
ci/pipeline.yml

We need a CI system and codeclimate. This commit adds it
Also remove the job group

Add necessary CI tools for cg repos

---

templates/mail/notify.txt
testdata/mail/notify/multiple_apps.txt
testdata/mail/notify/single_app.txt

Hand-wrapped text in a more logical order, with commands ready for copy-and-paste.

More logical flow with copy-pasta commands, plus artisanal hand-wrapping

---

main.go

Handles errors around apps that are deleted between listing apps and
checking droplets.
https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-10748

Log error and continue when droplet not found.

---

templates/mail/notify.txt

Suggestion for the upgrade email. I do like the conciseness of the current emails. I hope this doesn't detract from that. :)

Add restage vs. redeploy information

---

ci/pipeline.yml
ci/run-tests.sh
mailer.go
main.go

Goes with https://github.com/18F/cg-sandbox/pull/18.

Optionally configure smtp trust.

---

.gitattributes
Gopkg.lock
ci/notify.yml

This also updates the pipeline parameters to be explicity for the notify task.

Update dependencies to resolve properly

---

main.go
main_test.go

- parse php buildpack versions better
- deduplicate buildpacks. fixes #32 
None

Dedupe buildpacks

---

templates/mail/notify.txt
testdata/mail/notify/multiple_apps.txt
testdata/mail/notify/single_app.txt

- Suggest rolling updates (h/t @mogul)
None

update to recommend rolling strategy

---

templates/mail/notify.txt
testdata/mail/notify/multiple_apps.txt
testdata/mail/notify/single_app.txt

- pipeline was broken due to failing tests. 
- test data did not match template output
-
None

expected test values dont match master template.

---

ci/pipeline.yml

- Updates from the deprecated pull request resource to the recommended resource
None

update pull-request resource type

---

ci/pipeline.yml

- Updates repo param to repository to align with requirements for the github-pr-resource
None

Fix parameter name

---

ci/pipeline.yml

- Remove the 'every' line that was used by the previous pull resource
- This fixes the pull-status-check part of the pipeline
None

Update pipeline to remove every field

---

ci/notify.yml
ci/pipeline.yml
ci/run-tests.yml

- Update pipeline to use hardened containers
- Use general-task image rather than go docker image
Updates the pipeline to use hardened containers

Update to use hardened containers

---

ci/pipeline.yml

- Fixes failing pull request check by specifying the image to use for the build task
None, just fixing the pipeline

fix pull request

---

ci/pipeline.yml

- Update time and git resources to use hardened images
Updating resources to use hardened images

use hardened images for time and git resources

---

go.mod
go.sum
main_test.go

- 18f/cg-buildpack-notify references updated
-
-
None

updated github references

---

ci/notify.sh
ci/notify.yml

- scripts need to point to correct place
- 
None

updated ci scripts

---

templates/mail/notify.txt

- url changed recently
-
-
broken link is less secure than unbroken link

update url for app maintenance

---

testdata/mail/notify/multiple_apps.txt
testdata/mail/notify/single_app.txt

- tests arent happy because email changed
-
-
van wont forget this time - this is just updates to tests

test emails also need updating
